### ISSUE TITLE
Checklist to release a package on CRAN

### ISSUE THREAD

**Issue by maurolepore** [forestgeo/learn#212]
.

**Comment by maurolepore** [comment]
````
Prepare for release:

* [ ] References added to DESCRIPITON e.g. `Zuleta et al. (2018) <doi:10.1007/s11104-018-3878-0>`

```
If there are references describing the methods in your package, 
please add these in the Description field of your DESCRIPTION file in 
the form
  authors (year) <doi:...>
  authors (year) <arXiv:...>
  authors (year, ISBN:...)
with no space after 'doi:', 'arXiv:' and angle brackets for auto-linking.
```

* [ ] Remove install/render-stage \Sexpr{} from helpfile or prebuild PDF manual.
* [ ] Check that description is informative
* [ ] Check licensing of included files
* [ ] Check that all `@author`s mentioned in docs are listed in DESCRIPTION
* [ ] usethis::use_cran_comments()
* [ ] devtools::check()
* [ ] rhub::check_for_cran()
    * [ ] windows
    * [ ] ubuntu
    * [ ] fedora
* [ ] devtools::check_win_devel()
* [ ] rhub::check_on_macos()
* [ ] rhub::check(platform = 'ubuntu-rchk')
* [ ] rhub::check_with_sanitizers()
* [ ] rhub::check(platform = "fedora-clang-devel")
* [ ] rhub::check(platform = "fedora-gcc-devel")
* [ ] rhub::check_on_solaris()
* [ ] Polish pkgdown reference index

Submit to CRAN:
  
* [ ] Remove badges
* [ ] usethis::use_version('major')
* [ ] revdep_check(num_workers = 4)
* [ ] Update cran-comments.md
* [ ] devtools::release()
* [ ] Approve email

Wait for CRAN...

* [ ] Accepted
* [ ] Tag
* [ ] GitHub release
* [ ] usethis::use_dev_version()
* [ ] Restore badges in README with `git revert --no-edit <sha that removed badges>`
* [ ] Update install instructions in README
* [ ] Merge

From https://github.com/forestgeo/learn/issues/212
`Adapted from https://github.com/r-lib/vroom/issues/83`
````
